import { Component } from '@angular/core';

@Component({
  selector: 'app-car-list',
  standalone: false,
  templateUrl: './car-list.html',
  styleUrl: './car-list.scss',
})
export class CarList {
  
  public carTypes = [
    { label: 'SUV', value: 'suv' },
    { label: 'Sedan', value: 'sedan' },
    { label: 'Hatchback', value: 'hatchback' },
  ];

  public priceRanges = [
    { label: '₹0 – ₹2,000/day', value: 'low' },
    { label: '₹2,000 – ₹5,000/day', value: 'mid' },
    { label: '₹5,000+/day', value: 'high' },
  ];

 protected carsList = [
  {
    id: 1,
    name: 'Creta',
    brand: 'Hyundai',
    type: 'SUV',
    pricePerDay: 2800,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    rating: 4.5,
    imageUrl: 'images/creta.jpg',
  },
  {
    id: 2,
    name: 'Seltos',
    brand: 'Kia',
    type: 'SUV',
    pricePerDay: 3000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    seats: 5,
    rating: 4.6,
    imageUrl: 'images/seltos.avif',
  },
  {
    id: 3,
    name: 'Swift',
    brand: 'Maruti',
    type: 'Hatchback',
    pricePerDay: 1500,
    fuelType: 'Petrol',
    transmission: 'Manual',
    seats: 5,
    rating: 4.3,
    imageUrl: 'images/swift.jpg',
  },
  {
    id: 4,
    name: 'Baleno',
    brand: 'Maruti',
    type: 'Hatchback',
    pricePerDay: 1700,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    rating: 4.4,
    imageUrl: 'images/baleno.jpg',
  },
  {
    id: 5,
    name: 'City',
    brand: 'Honda',
    type: 'Sedan',
    pricePerDay: 2400,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    rating: 4.6,
    imageUrl: 'images/city.jpg',
  },
  {
    id: 6,
    name: 'Verna',
    brand: 'Hyundai',
    type: 'Sedan',
    pricePerDay: 2600,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    rating: 4.5,
    imageUrl: 'images/verna.jpg',
  },
  {
    id: 7,
    name: 'XUV700',
    brand: 'Mahindra',
    type: 'SUV',
    pricePerDay: 3500,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    seats: 7,
    rating: 4.7,
    imageUrl: 'images/xuv 700.jpg',
  },
  {
    id: 8,
    name: 'Scorpio N',
    brand: 'Mahindra',
    type: 'SUV',
    pricePerDay: 3800,
    fuelType: 'Diesel',
    transmission: 'Manual',
    seats: 7,
    rating: 4.6,
    imageUrl: 'images/scorpio.jpg',
  },
  {
    id: 9,
    name: 'Innova Crysta',
    brand: 'Toyota',
    type: 'SUV',
    pricePerDay: 4200,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    seats: 7,
    rating: 4.8,
    imageUrl: 'images/innova crysta.jpg',
  },
  {
    id: 10,
    name: 'Fortuner',
    brand: 'Toyota',
    type: 'SUV',
    pricePerDay: 5500,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    seats: 7,
    rating: 4.9,
    imageUrl: 'images/fortuner.jpg',
  },
];


}
