import { Component } from '@angular/core';

@Component({
  selector: 'app-car-list',
  standalone: false,
  templateUrl: './car-list.html',
  styleUrl: './car-list.scss',
})
export class CarList {
  public carTypes = [
    { label: 'SUV', value: 'suv' },
    { label: 'Sedan', value: 'sedan' },
    { label: 'Hatchback', value: 'hatchback' },
  ];

  public priceRanges = [
    { label: '₹0 – ₹2,000/day', value: 'low' },
    { label: '₹2,000 – ₹5,000/day', value: 'mid' },
    { label: '₹5,000+/day', value: 'high' },
  ];

  public carsList: object[] = [
    {
      id: 1,
      name: 'Creta',
      brand: 'Hyundai',
      type: 'SUV',
      pricePerDay: 2800,
      fuelType: 'Petrol',
      transmission: 'Automatic',
      seats: 5,
      rating: 4.5,
      imageUrl: 'assets/cars/creta.jpg',
    },
    {
      id: 2,
      name: 'Seltos',
      brand: 'Kia',
      type: 'SUV',
      pricePerDay: 3000,
      fuelType: 'Diesel',
      transmission: 'Automatic',
      seats: 5,
      rating: 4.6,
      imageUrl: 'assets/cars/seltos.jpg',
    },
    {
      id: 3,
      name: 'Swift',
      brand: 'Maruti',
      type: 'Hatchback',
      pricePerDay: 1500,
      fuelType: 'Petrol',
      transmission: 'Manual',
      seats: 5,
      rating: 4.3,
      imageUrl: 'assets/cars/swift.jpg',
    },
    {
      id: 4,
      name: 'Baleno',
      brand: 'Maruti',
      type: 'Hatchback',
      pricePerDay: 1700,
      fuelType: 'Petrol',
      transmission: 'Automatic',
      seats: 5,
      rating: 4.4,
      imageUrl: 'assets/cars/baleno.jpg',
    },
    {
      id: 5,
      name: 'City',
      brand: 'Honda',
      type: 'Sedan',
      pricePerDay: 2400,
      fuelType: 'Petrol',
      transmission: 'Automatic',
      seats: 5,
      rating: 4.6,
      imageUrl: 'assets/cars/city.jpg',
    },
    {
      id: 6,
      name: 'Verna',
      brand: 'Hyundai',
      type: 'Sedan',
      pricePerDay: 2600,
      fuelType: 'Petrol',
      transmission: 'Automatic',
      seats: 5,
      rating: 4.5,
      imageUrl: 'assets/cars/verna.jpg',
    },
    {
      id: 7,
      name: 'XUV700',
      brand: 'Mahindra',
      type: 'SUV',
      pricePerDay: 3500,
      fuelType: 'Diesel',
      transmission: 'Automatic',
      seats: 7,
      rating: 4.7,
      imageUrl: 'assets/cars/xuv700.jpg',
    },
    {
      id: 8,
      name: 'Scorpio N',
      brand: 'Mahindra',
      type: 'SUV',
      pricePerDay: 3800,
      fuelType: 'Diesel',
      transmission: 'Manual',
      seats: 7,
      rating: 4.6,
      imageUrl: 'assets/cars/scorpio-n.jpg',
    },
    {
      id: 9,
      name: 'Innova Crysta',
      brand: 'Toyota',
      type: 'SUV',
      pricePerDay: 4200,
      fuelType: 'Diesel',
      transmission: 'Automatic',
      seats: 7,
      rating: 4.8,
      imageUrl: 'assets/cars/innova.jpg',
    },
    {
      id: 10,
      name: 'Fortuner',
      brand: 'Toyota',
      type: 'SUV',
      pricePerDay: 5500,
      fuelType: 'Diesel',
      transmission: 'Automatic',
      seats: 7,
      rating: 4.9,
      imageUrl: 'assets/cars/fortuner.jpg',
    },
    {
      id: 11,
      name: 'i20',
      brand: 'Hyundai',
      type: 'Hatchback',
      pricePerDay: 1800,
      fuelType: 'Petrol',
      transmission: 'Manual',
      seats: 5,
      rating: 4.4,
      imageUrl: 'assets/cars/i20.jpg',
    },
    {
      id: 12,
      name: 'Punch',
      brand: 'Tata',
      type: 'SUV',
      pricePerDay: 1600,
      fuelType: 'Petrol',
      transmission: 'Manual',
      seats: 5,
      rating: 4.2,
      imageUrl: 'assets/cars/punch.jpg',
    },
    {
      id: 13,
      name: 'Nexon',
      brand: 'Tata',
      type: 'SUV',
      pricePerDay: 2300,
      fuelType: 'Electric',
      transmission: 'Automatic',
      seats: 5,
      rating: 4.5,
      imageUrl: 'assets/cars/nexon-ev.jpg',
    },
    {
      id: 14,
      name: 'Altroz',
      brand: 'Tata',
      type: 'Hatchback',
      pricePerDay: 1600,
      fuelType: 'Diesel',
      transmission: 'Manual',
      seats: 5,
      rating: 4.3,
      imageUrl: 'assets/cars/altroz.jpg',
    },
    {
      id: 15,
      name: 'Slavia',
      brand: 'Skoda',
      type: 'Sedan',
      pricePerDay: 2900,
      fuelType: 'Petrol',
      transmission: 'Automatic',
      seats: 5,
      rating: 4.6,
      imageUrl: 'assets/cars/slavia.jpg',
    },
    {
      id: 16,
      name: 'Virtus',
      brand: 'Volkswagen',
      type: 'Sedan',
      pricePerDay: 3000,
      fuelType: 'Petrol',
      transmission: 'Automatic',
      seats: 5,
      rating: 4.6,
      imageUrl: 'assets/cars/virtus.jpg',
    },
    {
      id: 17,
      name: 'Harrier',
      brand: 'Tata',
      type: 'SUV',
      pricePerDay: 3600,
      fuelType: 'Diesel',
      transmission: 'Automatic',
      seats: 5,
      rating: 4.7,
      imageUrl: 'assets/cars/harrier.jpg',
    },
    {
      id: 18,
      name: 'Compass',
      brand: 'Jeep',
      type: 'SUV',
      pricePerDay: 4000,
      fuelType: 'Diesel',
      transmission: 'Automatic',
      seats: 5,
      rating: 4.6,
      imageUrl: 'assets/cars/compass.jpg',
    },
    {
      id: 19,
      name: 'Camry',
      brand: 'Toyota',
      type: 'Luxury',
      pricePerDay: 6500,
      fuelType: 'Petrol',
      transmission: 'Automatic',
      seats: 5,
      rating: 4.9,
      imageUrl: 'assets/cars/camry.jpg',
    },
    {
      id: 20,
      name: 'BMW 3 Series',
      brand: 'BMW',
      type: 'Luxury',
      pricePerDay: 8500,
      fuelType: 'Petrol',
      transmission: 'Automatic',
      seats: 5,
      rating: 5.0,
      imageUrl: 'assets/cars/bmw-3.jpg',
    },
  ];
}
